spring:
  application:
    name: lomeone-server

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

server:
  shutdown: graceful

cloud:
  aws:
    region: ap-northeast-2

texhol:
  database:
    datasource:
      primary:
        secret-id: prod/texhol-db-credentials
        hostname: 132.226.227.63
        port: 3306
        database-name: texhol
        driver-class-name: com.mysql.cj.jdbc.Driver
      read-only:
        secret-id: prod/texhol-db-credentials
        hostname: 132.226.227.63
        port: 3306
        database-name: texhol
        driver-class-name: com.mysql.cj.jdbc.Driver

moyemap:
  database:
    datasource:
      primary:
        secret-id: prod/moyemap-db-credentials
        hostname: 132.226.227.63
        port: 3306
        database-name: moyemap
        driver-class-name: com.mysql.cj.jdbc.Driver
      read-only:
        secret-id: prod/moyemap-db-credentials
        hostname: 132.226.227.63
        port: 3306
        database-name: moyemap
        driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: INFO
