container:
  activeProfile: "staging"

image:
  tag: staging

service:
  internal: true
  annotations: {}

ingress:
  hosts:
    - host: staging-server.lomeone.com
      paths:
          - path: /
            pathType: ImplementationSpecific
  annotations: {}

resources:
  requests:
    cpu: 0.1
    memory: 1Gi

  limits:
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
