name: Feature Test

on:
  push:
    branches: [ feature/** ]

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
  packages: read    # This is required for installing dependencies

jobs:
  test:
    name: Test feature
    uses: lomeone/github-action/.github/workflows/gradle-test.yaml@main
    secrets: inherit
