name: Staging Deploy

on:
  push:
    tags: [ stg ]

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
  packages: read    # This is required for installing dependencies

jobs:
  deploy:
    environment: stg
    name: Deploy stg
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credential
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ECR_PUSH_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Install aws cli
        run: |
          if command -v aws >/dev/null 2>&1; then
            echo "AWS CLI already installed"
            aws --version
            exit 0
          fi
          
          echo "Installing AWS CLI"
          curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          
          aws --version

      - name: Move stg image tag
        run: |
          export MANIFEST=$(aws ecr batch-get-image --repository-name lomeone-server --image-ids imageTag=${GITHUB_SHA::10} --query 'images[].imageManifest' --output text)
          aws ecr put-image --repository-name lomeone-server --image-tag stg --image-manifest $MANIFEST
